server {
    listen 80;
    server_name cobblerscoders.tech www.cobblerscoders.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cobblerscoders.tech www.cobblerscoders.tech;

    ssl_certificate     /etc/letsencrypt/live/cobblerscoders.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cobblerscoders.tech/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:5046;
        proxy_set_header Host $host;
    }

    location /hub/ {
        proxy_pass http://backend:5046;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
